"""SessionEnd hook (meta-learner): durable forward-looking handoff + close dirty-bit.

OPT-IN: no-op unless the project ships `.claude/meta-learner.json`. The per-session
diary belongs on SessionEnd, not Stop (Stop fires every turn). Writes a
deterministic skeleton (branch, git status, signal count) only when the session
left uncommitted work OR captured signals; otherwise just flips the dirty-bit so
the next SessionStart knows the session ended cleanly. Fails open (exit 0).
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import meta_util as u  # noqa: E402


def _close_clean(extra=None) -> None:
    st = u.read_state()
    st["status"] = "clean_exit"
    st["last_turn_at"] = u.now_iso()
    if extra:
        st.update(extra)
    u.write_state(st)


def main() -> int:
    cfg = u.load_config()
    if cfg is None:
        return 0

    inp = u.read_stdin_json()
    reason = inp.get("reason", "")

    status = u.git("status", "--porcelain")
    dirty = bool(status.strip())
    nsig = u.queue_count()

    if not dirty and nsig == 0:
        _close_clean()
        return 0

    stamp = u.stamp()
    rel = os.path.join(*u.SESSIONS_DIR, f"{stamp}.md")
    path = u.p(rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)

    n_changed = len([ln for ln in status.splitlines() if ln.strip()])
    radar = u.radar(cfg)
    body = f"""# Session handoff — {u.now_iso()}

- **Branch:** {u.branch()}
- **End reason:** {reason or "(unspecified)"}
- **Uncommitted at close:** {n_changed} path(s)
- **Signals captured this session:** {nsig} (`learning/queue/signals.jsonl`)

## Git status at close
```
{status.strip() or "(clean)"}
```

## Next steps / open decisions
_Deterministic skeleton — the hook cannot read intent. Enrich via /psotobverse-utils:reflect or edit by hand._
- [ ] Run /psotobverse-utils:reflect to triage the {nsig} captured signal(s) into LEARNING_LOG / PLAYBOOK / {radar}.
- [ ] Confirm the uncommitted work above is intended (checkpoint or discard).

> Auto-generated by the SessionEnd hook. Mechanical facts above are reliable;
> the "next steps" are placeholders until a human/agent fills them.
"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(body)

    index = u.p(*u.SESSIONS_DIR, "INDEX.md")
    new_index = not os.path.exists(index)
    with open(index, "a", encoding="utf-8") as f:
        if new_index:
            f.write("# Session handoffs — index (newest at bottom)\n\n")
        f.write(f"- [{u.now_iso()}]({stamp}.md) — {u.branch()}, {n_changed} uncommitted, {nsig} signals\n")

    _close_clean({"last_handoff": rel.replace("\\", "/")})
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception:  # fail open
        sys.exit(0)
